name: Build and release

on:
  workflow_dispatch:
  release:
    types:
      - released

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - arch_name: armeabi-v7a
            arch_code: 0
          # - arch_name: x86
          #   arch_code: 1
          - arch_name: arm64-v8a
            arch_code: 2
          # - arch_name: x86_64
          #   arch_code: 3
      fail-fast: false

    steps:
      - name: Remove unused packages
        run: |
          pwd
          df -h
          sudo apt update
          sudo apt autopurge -y apache2* bind9* clang* cpp* cryptsetup* dotnet* ~n^gcc-[0-9]+$ gfortran* gir* g++* google* imagemagick* lld* lldb* microsoft* moby* mono* mssql* mysql* nginx* php* postgresql* r-base* r-cran* rpm* ruby* temurin*
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /usr/local/lib/android
          sudo swapoff -a
          sudo fallocate -l 7G /mnt/swapfile
          sudo mkswap /mnt/swapfile
          sudo swapon /mnt/swapfile
      # - name: Maximize build space
      #   uses: easimon/maximize-build-space@master
      #   with:
      #     overprovision-lvm: true
      #     root-reserve-mb: 4096
      #     temp-reserve-mb: 100
      #     swap-size-mb: 7168
      #     remove-dotnet: 'true'
      #     remove-android: 'true'
      #     remove-haskell: 'true'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run build script
        run: sudo ./build.sh ${{ matrix.arch_code }}
      - name: Upload workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch_name }}
          path: |
            /tmp/app-${{ matrix.arch_name }}-release-unsigned.apk
      - name: Upload release assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "/tmp/app-${{ matrix.arch_name }}-release-unsigned.apk"
          tag: ${{ github.ref }}
          overwrite: true
