name: Build and release

on:
  workflow_dispatch:
  release:
    types:
      - released

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - platform: AArch64
            target_arch: armv8-a
            target_cpu: generic
            optimize_level: 3
          - platform: AArch64
            target_arch: armv8.2-a
            target_cpu: cortex-a55
            optimize_level: fast
      fail-fast: false

    steps:
      - name: Remove unused packages
        run: |
          pwd
          df -h
          sudo apt update
          sudo apt autopurge -y apache2* bind9* clang* cpp* cryptsetup* dotnet* ~n^gcc-[0-9]+$ gfortran* gir* g++* google* imagemagick* lld* lldb* microsoft* moby* mono* mssql* mysql* nginx* php* postgresql* r-base* r-cran* rpm* ruby* temurin*
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /usr/local/lib/android
          sudo swapoff -a
          sudo fallocate -l 7G /mnt/swapfile
          sudo mkswap /mnt/swapfile
          sudo swapon /mnt/swapfile
          df -h
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: sudo ./build.sh -p ${{ matrix.platform }} -a ${{ matrix.target_arch }} -t ${{ matrix.target_cpu }} -o ${{ matrix.optimize_level }}
      - name: Upload workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-${{ matrix.target_cpu }}
          path: |
            /tmp/app-${{ matrix.platform }}-release-unsigned.apk
      - name: Upload release assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "/tmp/app-${{ matrix.platform }}-release-unsigned.apk"
          asset_name: app-${{ matrix.platform }}-${{ matrix.target_cpu }}-release-unsigned.apk
          tag: ${{ github.ref }}
          overwrite: true
